global:
  scrape_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: bot
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: [ "host.docker.internal:8090" ]

  - job_name: scrapper
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: [ "host.docker.internal:8091" ]
