name: Docker Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - grafana

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push bot image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./bot/bot.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bot:latest

      - name: Build and push scrapper image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./scrapper/scrapper.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/scrapper:latest
